<?php // Generated by CuyZ\Valinor\Cache\FileSystemCache
return fn (array $transformers, CuyZ\Valinor\Normalizer\Transformer\Transformer $delegate) => new class ($transformers, $delegate) implements CuyZ\Valinor\Normalizer\Transformer\Transformer {
    private array $transformers;

    private CuyZ\Valinor\Normalizer\Transformer\Transformer $delegate;

    public function __construct(array $transformers, CuyZ\Valinor\Normalizer\Transformer\Transformer $delegate)
    {
        $this->transformers = $transformers;
        $this->delegate = $delegate;
    }

    public function transform(mixed $value): mixed
    {
        $references = new WeakMap();
        return $this->transform_object_cuyz_valinor_tests_integration_normalizer_classwithshapedlist_5ad96612($value, $references);
    }

    private function transform_object_cuyz_valinor_tests_integration_normalizer_classwithshapedlist_5ad96612(CuyZ\Valinor\Tests\Integration\Normalizer\ClassWithShapedList $value, WeakMap $references): array
    {
        if (isset($references[$value])) {
            throw new CuyZ\Valinor\Normalizer\Exception\CircularReferenceFoundDuringNormalization($value);
        }
        $references = clone $references;
        $references[$value] = $value;
        $values = [
            'values' => $value->values,
        ];
        $transformed = [];
        $transformed['values'] = $this->transform_shaped_list_9a5d81a1($values['values'], $references);
        return $transformed;
    }

    private function transform_mixed(mixed $value, WeakMap $references): mixed
    {
        if (\is_bool($value)) {
            return $value;
        }
        if (\is_float($value)) {
            return $value;
        }
        if (\is_int($value)) {
            return $value;
        }
        if (\is_string($value)) {
            return $value;
        }
        if ($value === NULL) {
            return NULL;
        }
        if ($value instanceof UnitEnum) {
            return $value instanceof BackedEnum ? $value->value : $value->name;
        }
        if ($value instanceof DateTime) {
            return $value->format('Y-m-d\\TH:i:s.uP');
        }
        if ($value instanceof DateTimeZone) {
            return $value->getName();
        }
        if (\is_iterable($value) && ! $value instanceof Generator) {
            return $this->transform_iterable_mixed_bf66259c($value, $references);
        }
        return $this->delegate->transform($value);
    }

    private function transform_iterable_mixed_bf66259c(iterable $value, WeakMap $references): iterable
    {
        if (\is_array($value)) {
            return \array_map(fn (mixed $item) => $this->transform_mixed($item, $references), $value);
        }
        return (function () use ($value, $references) {
            foreach ($value as $key => $item) {
                yield $key => $this->transform_mixed($item, $references);
            }
        })();
    }

    private function transform_unsure_string_6a11bcce(mixed $value, WeakMap $references): mixed
    {
        if (! (\is_string($value))) {
            return $this->transform_mixed($value, $references);
        }
        return $value;
    }

    private function transform_unsure_int_c53673f7(mixed $value, WeakMap $references): mixed
    {
        if (! (\is_int($value))) {
            return $this->transform_mixed($value, $references);
        }
        return $value;
    }

    private function transform_shaped_list_9a5d81a1(array $value, WeakMap $references): array
    {
        $result = [];
        foreach ($value as $key => $item) {
            $result[$key] = match ($key) {
                0 => $this->transform_unsure_string_6a11bcce($item, $references),
                1 => $this->transform_unsure_int_c53673f7($item, $references),
                default => $this->transform_mixed($item, $references),
            };
        }
        return $result;
    }
};
