<?php // Generated by CuyZ\Valinor\Cache\FileSystemCache
return fn (array $transformers, CuyZ\Valinor\Normalizer\Transformer\Transformer $delegate) => new class ($transformers, $delegate) implements CuyZ\Valinor\Normalizer\Transformer\Transformer {
    private array $transformers;

    private CuyZ\Valinor\Normalizer\Transformer\Transformer $delegate;

    public function __construct(array $transformers, CuyZ\Valinor\Normalizer\Transformer\Transformer $delegate)
    {
        $this->transformers = $transformers;
        $this->delegate = $delegate;
    }

    public function transform(mixed $value): mixed
    {
        $references = new WeakMap();
        return $this->transform_iterable_stdclass_8fe5e53a83cbf2f3b41ad249eab32395($value, $references);
    }

    private function transform_mixed(mixed $value, WeakMap $references): mixed
    {
        if (\is_bool($value)) {
            return $value;
        }
        if (\is_float($value)) {
            return $value;
        }
        if (\is_int($value)) {
            return $value;
        }
        if (\is_string($value)) {
            return $value;
        }
        if ($value === NULL) {
            return NULL;
        }
        if ($value instanceof UnitEnum) {
            return $value instanceof BackedEnum ? $value->value : $value->name;
        }
        if ($value instanceof DateTime) {
            return $value->format('Y-m-d\\TH:i:s.uP');
        }
        if ($value instanceof DateTimeZone) {
            return $value->getName();
        }
        if (\is_iterable($value) && ! $value instanceof Generator) {
            return $this->transform_iterable_mixed_070660c7e72aa3e14a93c1039279afb6($value, $references);
        }
        return $this->delegate->transform($value);
    }

    private function transform_iterable_mixed_070660c7e72aa3e14a93c1039279afb6(iterable $value, WeakMap $references): iterable
    {
        if (\is_array($value)) {
            return \array_map(fn (mixed $item) => $this->transform_mixed($item, $references), $value);
        }
        return (function () use ($value, $references) {
            foreach ($value as $key => $item) {
                yield $key => $this->transform_mixed($item, $references);
            }
        })();
    }

    private function transform_stdclass(stdClass $value, WeakMap $references): mixed
    {
        $values = (array)$value;
        if ($values === []) {
            return CuyZ\Valinor\Normalizer\Transformer\EmptyObject::get();
        }
        return \array_map(fn (mixed $value) => $this->transform_mixed($value, $references), (array)$value);
    }

    private function transform_unsure_stdclass_8fe5e53a83cbf2f3b41ad249eab32395(mixed $value, WeakMap $references): mixed
    {
        if (! ($value instanceof stdClass)) {
            return $this->transform_mixed($value, $references);
        }
        return $this->transform_stdclass($value, $references);
    }

    private function transform_iterable_stdclass_8fe5e53a83cbf2f3b41ad249eab32395(iterable $value, WeakMap $references): iterable
    {
        if (\is_array($value)) {
            return \array_map(fn (mixed $item) => $this->transform_unsure_stdclass_8fe5e53a83cbf2f3b41ad249eab32395($item, $references), $value);
        }
        return (function () use ($value, $references) {
            foreach ($value as $key => $item) {
                yield $key => $this->transform_unsure_stdclass_8fe5e53a83cbf2f3b41ad249eab32395($item, $references);
            }
        })();
    }
};
