name: Benchmark
on: [pull_request]
jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    env:
      php-version: '8.3'
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.php-extensions }}
          ini-values: zend.assertions=1
          coverage: none # Xdebug is installed by default, so we remove it manually

      - uses: "ramsey/composer-install@v2"

      - name: Creating a baseline benchmark from target branch
        run: composer run-script benchmark-baseline

      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          clean: false

      - uses: "ramsey/composer-install@v2"

      - name: Compare the performances against the baseline
        run: composer run-script benchmark-compare
